### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by emilylange**
Hi! :)
This PR adds a somewhat basic Dockerfile. That means there is now another (and IMHO easier) way to install this lovely software.

However, there is currently no doc, because I am unsure whether you want to (auto-) build and publish this docker image to hub.docker.com (or similar). 
Depending on what you decide for I would then add a little notice/doc/explaination to the README.

If you have any questions, feel free to ask them :)

### CODE REVIEW

**Comment by mbugert** [comment]
Hi @IndeedNotJames,

good idea, thanks for the PR. I'm not so well-versed with docker, but that's about to change I guess.

One slight issue I'm seeing is that the port can be configured in the YAML (which I would like to keep it this way), but in the Dockerfile it's hardcoded. Do you have an idea how this could be kept configurable and in sync?

I think I would want to choose the autobuild to Docker Hub route. Some documentation in the README on that would be highly appreciated. :blush:

**Comment by emilylange** [comment]
Hi, sorry for the late reply.

The port is not hardcoded in a way you might think. 
Quote from [Docker Docs](https://docs.docker.com/engine/reference/builder/#expose):

> The `EXPOSE` instruction **does not actually publish the port**. It functions as a type of **documentation between the person who builds the image and the person who runs the container**, about which ports are intended to be published. **To actually publish the port when running the container, use the `-p` flag on** `docker run` to publish and map one or more ports...

`EXPOSE` has no impact whatsoever.
_However, as far as I know that was a bit different in the past (many years ago). Nowadays, containers can reach any of each others services by default as long as they are on the same docker network._

Think of the following `docker run` template for this Dockerfile:
```bash
docker run --publish $hostPort:$PortInsideContainerFromConfig --volume $StorageVolumeName $dockerImage
```

```bash
docker run -p 1234:9705 -v connectbox-data mbugert/connectbox-prometheus
```
This would expose the port `:9705` from inside the container to `0.0.0.0:1234` on host (so any interface).
Some might only want to bind the host port to localhost `-p 127.0.0.1:1234:9705` or to none at all and use container-to-container connections, which don't need any `-p` at all and work without any interaction.

Using another port (e.g. `:1337`) inside the container by modifying the `config.yml` would lead to `-p 1234:1337` to bind the port `:1337` from inside the container to `0.0.0.0:1234` on host.

I hope this clarifies things. If not, ask again :)



Anyway, I just realized this very Dockerfile might not be the best for a build pipe, since it takes the latest version from `pip`.
Do you publish the releases to `pip` manually? I never worked with `pip` before to actually publish something :thinking:.
If so, do you publish them before pushing a new release on github?
Anyway, do you think the docker image should build from source instead of pulling from `pip`?

Actually setting up auto build for hub.docker.com is fairly straight forward. See https://docs.docker.com/docker-hub/builds/


PS: Do you want to chat somewhere else (in realtime and German lol) e.g. matrix.org/discord/telegram? :P

**Comment by wojciech-z** [comment]
Hi!

First of all, great job @mbugert and thank you @IndeedNotJames for providing the Docker integration!

I've actually used your Dockerfile and docker-run.sh files to run this on my machine, but I had to change few things first, most notably how I provide the config file.

I think it would be really cool if the config parameters could be read from environment variables (each parameter as a separate variable). Docker (and docker-compose) has nice support for it and it would remove the requirement of having a /data volume just for config. Maybe check envs only if config.yml is not found? That way you could support both approaches.

As for the `pip` - Dockerfile should definitely build from local source, if you apply the PR in current state, then `docker build` will basically ignore local changes and download from pip instead

**Comment by emilylange** [comment]
Hi @wojciech-z!
That sounds like you already patched those files to use env vars? Did you? Otherwise, I'll make that quick.

Anyway, I'll change it to build from source.

**Comment by wojciech-z** [comment]
I've created my own fork with those fixes:
https://github.com/wojciech-z/connectbox-prometheus/blob/docker/Dockerfile
https://github.com/wojciech-z/connectbox-prometheus/blob/docker/docker-run.sh

I didn't patch the application itself, only added support to docker-run.sh

**Comment by emilylange** [comment]
I am sort of unhappy how we could implement env vars properly without some workarounds in the `docker-run.sh` file which could lead to inconsistency eventually.

I find what @wojciech-z did in his [`docker-run.sh`](https://github.com/wojciech-z/connectbox-prometheus/blob/docker/docker-run.sh) is kinda sketchy, but a great idea. It's just that I don't find it's a clean and proper solution and will eventually stop working if nobody keeps and eye on this.

I worked a bit on an alternative where it would still copy that `config.yml` from the sources and `sed -i -e` the file to replace the default values with those from the env vars, if specified.
However, I found that even more hack-y, so I didn't commit it.

I did a bit of research on the actual python code and found out the used `click` lib does support env vars for both [parameters](https://click.palletsprojects.com/en/7.x/arguments/#environment-variables) (used for specifying the config filename) and [--options](https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables).

So IMHO the proper way would be to patch the src and support the usual `config.yml` (making it `, required=False)` [here](https://github.com/mbugert/connectbox-prometheus/blob/a16966bd17e47fdbd3ead97d51eb47bfb39ba59f/connectbox_exporter/connectbox_exporter.py#L128))  but also exposing every option to a `--option` (and so to env vars).

@mbugert are you okay with that? If so, should I do that in a separate PR or do you want to do that?

**Comment by mbugert** [comment]
> Hi, sorry for the late reply.

Likewise. Thank you for spending your time on this @IndeedNotJames.

> the used click lib does support env vars for both parameters [...] and --options.

Nice find, I didn't know that. Still, following this route would mean that one would need to maintain all config parameters in two locations which I would want to avoid.
I agree that having to plug in an external config file is more cumbersome when using Docker, but it's the common approach for most prometheus exporters.

I think the best solution would be to build the docker image from source (as @wojciech-z mentioned) and not publish the docker images to dockerhub. A similar solution is being used for the official [ipmi exporter](https://github.com/soundcloud/ipmi_exporter).

Would you mind updating the dockerfile and the readme with some copy-paste-friendly docker commands for this solution? I created a `dev` branch so we don't taint the master branch with WIP changes.

**Review by mbugert — APPROVED** [review]

**Comment by mbugert** [comment]
Wonderful, thanks a lot!

**Pull request merged**
